### ISSUE TITLE
Project Spec

### ISSUE THREAD

**Issue by yiming330** [yiming330/power-shine#2]
1.  About Page (Company Profile)
2.  Contact Information
3.  Product Category
       ➢ Valves: 2 layer
            i. Process (1 page with texts and images, editable with text editor in admin interface)
            ii.    Product (4~5 subcategories, fixed subcategories, can use tags)
                • Subcategory 1
                • Subcategory 2
                • …
       ➢ Casting: 1 layer
            i. Process (1 page with texts and images, editable with text editor in admin interface)
            ii.    Product (No subcategory needed)
   
   ```
   ➢ Moulds: 1 layer
        i. Process (1 page with texts and images, editable with text editor in admin interface)
        ii.    Product (No subcategory needed)
   ```
4.  Product Detail
        ➢ Valves: Title, Description, Material (text box), images, chart (table)
        ➢ Casting: Production Process
        ➢ Moulds: Title, Description, Material (text box), images
        ➢ Spec Chart: With fixed columns (about 30 columns) to fill out in the admin interface, and the front end will populate a table based on the columns that have been entered data.

**Comment by yiming330** [comment]
About:
http://htmlstream.com/preview/unify/page_about1.html
Contact:
http://htmlstream.com/preview/unify/page_contact1.html
Product Listing:
http://htmlstream.com/preview/unify/portfolio_text_blocks.html
Product Detail:
http://htmlstream.com/preview/unify/portfolio_item.html

**Comment by wuboy0307** [comment]
done

**Comment by yiming330** [comment]
Confirmed.
