### ISSUE TITLE
Product Listing Page

### ISSUE THREAD

**Issue by yiming330** [yiming330/power-shine#5]
Category Levels:
1. Valves
    1.1 Ball Valves
    1.2 Check Valves
    1.3 Gate Valves
    1.4 Butterfly Valves
1. Fittings
   2.1 Stainless Steel Cast Fitting 150 LBS
   2.2 Forged Stainless Steel / Carbon Steel Fittings 2000/3000/6000 LBS
2. Casting
   3.1 Investment Casting (Lost-Wax Process)
   3.2 Sand Casting / Shell Mold Casting
3. Molds
   4.1 Gravity Casting Mold
   4.2 Investment Casting Mold
   4.3 Shell Mold / Sand Casting
   4.4 Automatic Molding - DISA

Level 1 template: (List 1., 2., 3., 4.)
http://htmlstream.com/preview/unify/portfolio_2_column.html

Level 2 template: (List 1.1, 1.2,....)
http://htmlstream.com/preview/unify/portfolio_2_column.html

Product Listing: (List products under the level 2 category)
http://htmlstream.com/preview/unify/portfolio_text_blocks.html

**Comment by yiming330** [comment]
Category Levels:
1. Valves
1.1 Ball Valves
1.2 Check Valves
1.3 Gate Valves
1.4 Butterfly Valves

Fittings
2.1 Cast Fitting 150 LBS
2.2 Forged Steel Fittings 2000/3000/6000 LBS

Casting
3.1 Investment Casting
3.2 Sand / Shell Mold Casting

Molds
4.1 Gravity Casting Mold
4.2 Investment Casting Mold
4.3 Shell Mold / Sand Casting
4.4 Automatic Molding - DISA

Level 1 template: (List 1., 2., 3., 4.)
http://htmlstream.com/preview/unify/portfolio_2_column.html

Level 2 uses tags and sorting function from the below template.
Product Listing: (List products and can be sorting by tags)
http://htmlstream.com/preview/unify/portfolio_text_blocks.html

**Comment by yiming330** [comment]
1. For main menu, keep the category list. But the user still wants a Listing page with level 1 categories.
2. Level 2 uses tags and sorting function from the below template.
   Product Listing: (List products and can be sorting by tags)
   http://htmlstream.com/preview/unify/portfolio_text_blocks.html
3. Add News (A text area in admin page) area under menu.
4. Add Material List (A text area in admin page) area under News.

A mockup page is attached.
![powershine_prodlist](https://cloud.githubusercontent.com/assets/5311668/2677921/c2ec939e-c159-11e3-9fc9-b75f4b8b08ba.png)

**Comment by wuboy0307** [comment]
Please edit in admin taxon

**Comment by yiming330** [comment]
1. Please add a border for News and Material as the mockup page. The border size shall be fixed. If the texts in the area are bigger than the border, add a scroll bar to roll the content.
2. For News and Material area, only appear on first level taxon. (Not on the second level page: like Ball valves.)

**Comment by wuboy0307** [comment]
fixed

**Comment by yiming330** [comment]
Confirmed.
