### ISSUE TITLE
Product Detail Page

### ISSUE THREAD

**Issue by yiming330** [yiming330/power-shine#6]
For product detail page:

Use:
http://htmlstream.com/preview/unify/portfolio_item.html

Field:
Item Name
Item Description
Item Images (multiple)

**Comment by wuboy0307** [comment]
done

**Comment by yiming330** [comment]
Please remove the following fields in the page:
http://ps.makeanegg.com/products/1-pc-ball-valves-screwed-end-800lb-1-000lb

 Jack Baur
 14,2003 February
 Websites, Google, HTML5/CSS3

"The box field in the bottom"

Et harum quidem rerum facilis est et expedita distinctio lorem ipsum dolor sit amet consectetur adipiscing elit. Ut non libero consectetur adipiscing elit magna. Sed et quam lacus. Fusce condimentum eleifend enim a feugiat. Pellentesque viverra vehicula sem ut volutpat.

**Comment by wuboy0307** [comment]
fixed

**Comment by yiming330** [comment]
Confirmed.
