### ISSUE TITLE
Add Quality Assurance section

### ISSUE THREAD

**Issue by yiming330** [yiming330/power-shine#7]
1. Add a showroom menu item
2. Add a Category item
3. For Quality Assurance items, it's exactly the same as product listing page.
   http://htmlstream.com/preview/unify/portfolio_text_blocks.html
   However, the items are non-clickable. (So there is no product detail page for Quality Assurance items)

**Comment by wuboy0307** [comment]
fix

**Comment by yiming330** [comment]
Issue closing.
