### ISSUE TITLE
Add Home Page

### ISSUE THREAD

**Issue by yiming330** [yiming330/power-shine#8]
Use Slide show images from the About page on the top

Use Product Category Images below the slide show images. Each image is clickable and link to the Product listing page.

A mockup page is attached.
![powershine_home](https://cloud.githubusercontent.com/assets/5311668/2678074/e46b8afa-c15b-11e3-9758-a086be1ac3a4.png)

**Comment by wuboy0307** [comment]
fix

**Comment by yiming330** [comment]
是否有辦法排除quality assurance? 如果無法排除, 也許讓一排顯示五個category, 以免現在第一排有四個, 第二排只有一個很怪

**Comment by wuboy0307** [comment]
改成只秀前四個

**Comment by yiming330** [comment]
Confirmed.
